services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3003:3003'
      - '3004:3004'
    volumes:
      - .:/usr/src/app
    networks:
      - glam_seven_network
    depends_on:
      - postgres

  product-service:
    build:
      context: .
      dockerfile: ./apps/product-service/Dockerfile
      target: development
    command: pnpm run start:dev product-service
    env_file:
      - ./apps/product-service/.env
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app
    networks:
      - glam_seven_network
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=glamseven
      - POSTGRES_USER=glam_seven_user
      - POSTGRES_DB=glam_seven_db
    networks:
      - glam_seven_network

volumes:
  postgres_data:

networks:
  glam_seven_network: